name: lenguaje
description: "Aplicación educativa e inclusiva para Lengua de Señas Peruana"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- UI y Navegación ---
  flutter_login: ^5.1.0      # Pantalla de login lista para usar
  go_router: ^14.0.0           # Navegación declarativa y fácil de mantener

  # --- Estado ---
  flutter_bloc: ^8.1.3         # Gestión de estado (puedes usar Riverpod si prefieres)
  equatable: ^2.0.5            # Comparación sencilla de objetos (útil con Bloc)

  # --- Autenticación ---
  firebase_core: ^3.6.0        # Inicializar Firebase
  firebase_auth: ^5.3.0        # Autenticación con Firebase
  google_sign_in: ^6.2.1       # Login con Google

  # --- Almacenamiento local ---
  shared_preferences: ^2.2.3   # Guardar datos simples (modo invitado, ajustes)
  hive: ^2.2.3                 # Base de datos local ligera
  hive_flutter: ^1.1.0

  # --- Multimedia e IA ---
  camera: ^0.11.0              # Acceso a la cámara
  tflite_flutter: ^0.10.4      # Ejecutar modelos TensorFlow Lite
  

  # --- Utilidades ---
  intl: ^0.19.0                # Formateo de fechas, números, etc.
  permission_handler: ^11.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0 # Asegúrate de tener mockito para simular dependencias
  bloc_test: ^9.1.5 # Crucial para probar Blocs
  build_runner: ^2.4.7  

flutter:
  uses-material-design: true
