// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT46_LFfvPyCaqFDttN6PFwumW3-zlQOs',
    appId: '1:376116854174:android:3d22c116f0d01471866a8f',
    messagingSenderId: '376116854174',
    projectId: 'lenguaje-c3e68',
    storageBucket: 'lenguaje-c3e68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGk_EeFS2HOtnVX2tYxY4BO8L74woP4N8',
    appId: '1:376116854174:ios:8a7dc92212ba00c6866a8f',
    messagingSenderId: '376116854174',
    projectId: 'lenguaje-c3e68',
    storageBucket: 'lenguaje-c3e68.firebasestorage.app',
    iosClientId: '376116854174-oqb1k3m7ipv85u7ej8809c7e2s461qh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lenguaje',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChbiWEEPyj9iPX1yoqKhzsOtZqE1kulHo',
    appId: '1:376116854174:web:3043f52bb304d73c866a8f',
    messagingSenderId: '376116854174',
    projectId: 'lenguaje-c3e68',
    authDomain: 'lenguaje-c3e68.firebaseapp.com',
    storageBucket: 'lenguaje-c3e68.firebasestorage.app',
    measurementId: 'G-B95FV9SEZ7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGk_EeFS2HOtnVX2tYxY4BO8L74woP4N8',
    appId: '1:376116854174:ios:8a7dc92212ba00c6866a8f',
    messagingSenderId: '376116854174',
    projectId: 'lenguaje-c3e68',
    storageBucket: 'lenguaje-c3e68.firebasestorage.app',
    iosClientId: '376116854174-oqb1k3m7ipv85u7ej8809c7e2s461qh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lenguaje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChbiWEEPyj9iPX1yoqKhzsOtZqE1kulHo',
    appId: '1:376116854174:web:3271df145f05956e866a8f',
    messagingSenderId: '376116854174',
    projectId: 'lenguaje-c3e68',
    authDomain: 'lenguaje-c3e68.firebaseapp.com',
    storageBucket: 'lenguaje-c3e68.firebasestorage.app',
    measurementId: 'G-B56955JL8H',
  );

}