name: lenguaje
description: "Aplicaci칩n educativa e inclusiva para Lengua de Se침as Peruana"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- UI y Navegaci칩n ---
  flutter_login: ^5.1.0
  go_router: ^14.0.0

  # --- Estado ---
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # --- Autenticaci칩n ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1

  # --- Almacenamiento local ---
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- Multimedia e IA ---
  camera: ^0.11.0
  tflite_flutter: ^0.11.0
  

  # --- Utilidades ---
  intl: ^0.19.0
  permission_handler: ^11.3.0
  image: ^4.0.17
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/actions_15.tflite
    - assets/words.json
    - assets/asl_dataset/
